language: node_js

node_js:
    - "stable"

cache:
    directories:
        - node_modules

script:
    - npm run test && npm run build:css && npm run build && cp CNAME build/CNAME

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
        branch: master
